title: "ERROR"
body:
  - type: checkboxes
    attributes:
      label: 작성자
      options:
        - label: "승현(PM)"
        - label: "정현(형상)"
        - label: "남규(DB)"
        - label: "관훈(DB)"

  - type: dropdown
    id: download
    attributes:
      label: 에러내용
      options:
        - "404 에러"
        - "500 에러"
        - "백엔드 기타 에러"
        - "프론트엔드 기타 에러"
    validations:
      required: true

  - type: textarea
    id: error_details
    attributes:
      label: 에러내역(자세히)
      description: "에러내역을 적어주세요.."
      value: ""
    validations:
      required: true

  - type: textarea
    id: solution_details
    attributes:
      label: 해결방안(자세히)
      description: "해결방안을 적어주세요.."
      value: ""
    validations:
      required: true
