title: "💼 [회의] YYYY-MM-DD | 제목"
body:
  - type: checkboxes
    attributes:
      label: 🙆‍♂️ **참여자** 👥
      options:
        - label: "승현(PM)"
        - label: "정현(형상)"
        - label: "남규(DB)"
        - label: "관훈(DB)"

  - type: textarea
    id: improvements
    attributes:
      label: 🌈 **회의 내역** 📋
      description: "회의 내용을 구체적으로 적어주세요.. ✍️"
      value: |
        📌 주요 논의 사항 : 
        💡 아이디어/결정 사항 : 
        ❤ 오늘할일 
               승현(PM) : 
               정현(형상) : 
               남규(DB) : 
               관훈(DB)
      render: bash
    validations:
      required: true
